### ISSUE TITLE
Feature Request: Export/Import function for preferences

### ISSUE THREAD

**Issue by MyCodeIsntWorking** [Slazanger/SMT#119]
The title says it all, we need a export/import function for the preferences we have made it.
After any update, all the preferences are at standart and we need to made it again.
This would be a great function.

**Comment by Slazanger** [comment]
What is actually needed is I need to add versioning to the preferences much like the characters; the layout,  anom data and preferences are tied to a version since they are a little version dependant.. 

The anom data can change now; the UI/layout is a way off; but the preferences should be a reasonably easy change

**Comment by Slazanger** [comment]
This will be resolved with 1.27
