### ISSUE TITLE
Bug: Auto follow Active Character does not work

### ISSUE THREAD

**Issue by andrewtquick** [Slazanger/SMT#144]
When Auto follow Active Character is checked, the map will not follow the active character. Once a character has selected in the Active Character drop down in the menu bar, the map will then start to follow the selected character. If no character is selected in the Active Character drop down, the Auto follow active character does not follow the active character. This is the same for ESI added characters and non-ESI added characters.

**Comment by Slazanger** [comment]
this is the expected behaviour, if you dont select a character to follow how will it know what to follow ? Unless im missing something ?

**Comment by andrewtquick** [comment]
In prior versions, if I didn't select a character in the drop down, and just had Auto follow enabled, the map would update to the currently active game session. When I had characters in different regions, the map would update to the region of the active game session.. It no longer does this. I have to manually click the drop down to select the character I want to follow, and with using Eve-O keybinds to quickly switch between characters, the map no longer updating to the active character makes it painful to keep track of the different characters.

**Comment by Slazanger** [comment]
The follow has never behaved like that.. do you mean the auto selecting of the active character based on the active eve window ?  this is the "auto sync character to active window" option.. if EVE-O is also renaming the client window titles (they should be in the format EVE - <Character Name> it will cause problems since thats what's used to determine which screen is in focus
