### ISSUE TITLE
Authorize issue

### ISSUE THREAD

**Issue by Queueyou** [Slazanger/SMT#34]
0.81 issue.  Put all in zip file into it's own folder, go to characters, add character.  Once complete, the app closes.  Character not added when re-opened.

**Comment by Paic** [comment]
Do you still have the problem with the [current latest release](https://github.com/Slazanger/SMT/releases/tag/SMT_101) ?

**Comment by keuric** [comment]
Not sure if original opener is still watching this, I came looking for a thread similar. I am seeing this issue.

1. Add Character
2. EVE login screen
3. Choose character
4. Click Authorize

Two things happen nearly at the same time, but not quite. The authorize attempt looks like it's going fine, but then it kicks to a localhost URL - http://localhost:8762/callback/?code=JPX3Ys4Y2kKN2XCTEmfNFA&state=SMT_102

Firefox (or Chrome) can't connect, then SMT.exe crashes.

**Comment by Paic** [comment]
The localhost URL is intended, it's part of the OAuth2 process for SMT to get a valid token for the character.

Can you please try to add a character from this menu instead of the `File > Characters > Add Character` :
![image](https://user-images.githubusercontent.com/940586/132124711-d5f5f973-1d78-4027-84f5-7323c50a89c1.png)

If this does not help, some people reported success after disabling their AV/Windows Defender.

**Comment by Slazanger** [comment]
this should be fixed in 1.03

**Comment by Queueyou** [comment]
Reloaded and tried this last night.  Worked fine for me.  Sorry for delays on responding and thank you for solving.
