### ISSUE TITLE
Departures to Windows 10 x 64

### ISSUE THREAD

**Issue by devfint** [Slazanger/SMT#36]
It is almost impossible to use on Windows 10 x 64. The program constantly crashes. Checked on two computers

How to recreate:
Add character
Double click on it to be in its system
And try to close the tab

P.S. I am writing through google translate

**Comment by Ebag333** [comment]
Using on Win10 x64.  There have been crashes, but it seems to be either tied to:

1. Version specific (certain versions were bad for crashing, current version seems stable)
2. Likely due to buffer/size, if you left it open and it collected large amounts of data, it'd eventually crash.  Not sure if anything has been done to address this yet.

**Comment by Paic** [comment]
Hey 👋Is this still relevant with the latests versions ?
