### ISSUE TITLE
No warning sound within dangerzone

### ISSUE THREAD

**Issue by Regicyde** [Slazanger/SMT#59]
I'm still using version .92 as it is the only one that gives me a warning sound when intel is reported within 5 jumps.  When I select Warning On Unknown it works as advertised. I have had this issue with version .93, .94 and now .95. Maybe I'm not checking the right boxes or something. I was hoping the issue would get resolved when a new version was released but we are 3 in and I'm still having the same problem so I figured I would leave a bug report.
Thanks

**Comment by fizch** [comment]
I am replying only because he helped me with this same issue earlier. There is a new character window in the right sidebar. That window lists all of the characters that you have setup for SMT to monitor. On the right side of each character is a checkbox for Danger zone. That needs to be checked for the alert to sound when intel is reported within the danger zone.

**Comment by Slazanger** [comment]
In v. 95 this moved from the characters panel on the right, to the new character window accessible from the main window
