### ISSUE TITLE
SMT 1.13 cant find jump gates

### ISSUE THREAD

**Issue by ZeRonin-de** [Slazanger/SMT#98]
the "find jump gates" button is "greyed out" so you cant find (new) jump gates.

**Comment by Slazanger** [comment]
This is intentional, the api this uses is so broken..

It doesnt return everything : https://github.com/esi/esi-issues/issues/108
What it does return is often dead, and the api's will tell you the structures are alive :  https://github.com/esi/esi-issues/issues/1129
and sometimes it just doesnt work :  https://github.com/esi/esi-issues/issues/1268

**Comment by Slazanger** [comment]
you can still add gates manually though

**Comment by Slazanger** [comment]
If you want to update the jump bridge list easily, follow these instructions:

Open the Structure Browser in-game
Select “Jump Bridges” and “Region”, make sure all services are deselected. (Always do a whole region at a time.)
Create a new chat channel for yourself
Drag and drop the first structure into the chat window as if you were linking it
Hit enter and repeat for every single jump bridge in that region
Right click and “Copy All”
Paste the list in a rich text editor

Once you have all of them, you can copy all the text and import from clipboard
